name: @name@
main: @main@
description: @description@
version: @version@
api-version: @api@
author: @author@

commands:
  bvn:
    description: Display player informations.
    usage: /bvn
    permission: svplayer.bvn
  svplayer:
    description: Plugin management command.
    aliases: [svp]
    usage: /svplayer reload
    permission: svplayer.admin

permissions:
  svplayer.*:
    children:
      svplayer.infos: true
      svplayer.mod: true
      svplayer.admin: true
  svplayer.infos:
    description: Allows seeing some player informations.
  svplayer.mod:
    description: Allows seeing more player informations.
  svplayer.admin:
    description: Allows managing the plugin.
